---
title: "Courses"
format:
  html:
    embed-resources: true
    page-layout: full
---

## General Overview

### Spring 2026
| Course | Description | Instructor | Units | Grade |
|--------|-------------|-----------|-------|-------|
| [COMPSCI 162](https://cs162.org/) | Operating Systems and System Programming | John Kubiatowicz, this link opens in new tab | 4.0 | IP |
| MATH 185 | Introduction to Complex Analysis | Ilia Nekrasov | 4.0 | IP |
| MCELLBI 50 | The Immune System and Disease | Anant Sahai, Gireeja Ranade | 4.0 | IP |
| UGBA 10X | Foundations of Business | Brandi Pearce, Harris Sondak, Jonathan Heyne, Queen Jaks | 3.0 | IP |

### Fall 2025
| Course | Description | Instructor | Units | Grade |
|--------|-------------|-----------|-------|-------|
| ASTRON C10 | Introduction to General Astronomy | Alexei Filippenko | 4.0 | P |
| [COMPSCI 180](https://cal-cs180.github.io/fa25/) | Intro to Computer Vision and Computational Photography | Alexei Efros, Angjoo Kanazawa | 4.0 | A |
| [COMPSCI C182](https://berkeley-cs182.github.io/fa25/index.html) | Designing, Visualizing and Understanding Deep Neural Networks | Anant Sahai, Gireeja Ranade | 4.0 | P |
| [COMPSCI 194](https://rdi.berkeley.edu/agentic-ai/f25) | Special Topics | Xiaodong Song | 1.0 | P |
| [EECS 183](https://cal-nlp-class.github.io/fa25/) | Natural Language Processing | Alane Suhr, Gopala Anumanchipalli | 4.0 | A+ |
| DATA 144 | Data Mining and Analytics | Zachary Pardos | 3.0 | A+ |


### Spring 2025
| Course | Description | Instructor | Units | Grade |
|--------|-------------|------------|-------|-------|
| CDSS 198 | Directed Group Studies for Advanced Undergraduates | - | 1.0 | P |
| [COMPSCI 168](https://sp25.cs168.io/) | Introduction to the Internet: Architecture and Protocols | Peyrin Kao, Sylvia Ratnasamy | 4.0 | A+ |
| [COMPSCI 189](https://people.eecs.berkeley.edu/~jrs/189/) | Introduction to Machine Learning | Jonathan Shewchuk | 4.0 | A+ |
| MATH 104 | Introduction to Analysis | Mengxuan Yang | 4.0 | A- |
| MELC 18 | Introduction to Ancient Egypt | Carol Redmount | 4.0 | A+ |

### Fall 2024
| Course | Description | Instructor | Units | Grade |
|--------|-------------|------------|-------|-------|
| [COMPSCI 186](https://cs186berkeley.net/) | Introduction to Database Systems | Alvin Cheung | 4.0 | A |
| [COMPSCI 375](https://cs375.github.io/su24/index.html) | Teaching Techniques for Computer Science | Victor Huang | 2.0 | P |
| DATA C104 | Human Contexts and Ethics of Data | Ari Edmundson, Cathryn Carson, Daniel Roddy | 4.0 | A- |
| [DATA C140](https://data140.org/) | Probability for Data Science | Ani Adhikari | 4.0 | A+ |
| MATH 128A | Numerical Analysis | Ming Gu | 4.0 | A+ |

### Spring 2024
| Course | Description | Instructor | Units | Grade |
|--------|-------------|------------|-------|-------|
| [COMPSCI 61C](https://inst.eecs.berkeley.edu/~cs61c/sp24/) | Great Ideas of Computer Architecture (Machine Structures) | Justin Yokota, Lisa Yan | 4.0 | A+ |
| [DATA C100](https://ds100.org/sp24/) | Principles & Techniques of Data Science | Joseph Gonzalez, Narges Norouzi | 4.0 | A+ |
| ESPM 169 | International Environmental Politics | Kate O'Neill | 4.0 | A+ |
| MATH 110 | Abstract Linear Algebra | Edward Frenkel | 4.0 | A |
| STAT 33B | Introduction to Advanced Programming in R | Gaston Sanchez Trujillo | 1.0 | A |
| UGIS 192B | Supervised Research: Social Sciences | - | 3.0 | P |

### Fall 2023
| Course | Description | Instructor | Units | Grade |
|--------|-------------|------------|-------|-------|
| [COMPSCI 188](https://inst.eecs.berkeley.edu/~cs188/fa23/) | Introduction to Artificial Intelligence | Igor Mordatch, Peyrin Kao | 4.0 | A+ |
| [COMPSCI 198](https://cubstart.com/) | Directed Group Studies for Advanced Undergraduates | Justin Wong, Andy Huang | 2.0 | P |
| DATA 198 GRP 005 | Directed Group Studies for Advanced Undergraduates | - | 2.0 | P |
| DATA 198 GRP 007 | Directed Group Studies for Advanced Undergraduates | - | 1.0 | P |
| DATA 198 GRP 012 | Directed Group Studies for Advanced Undergraduates | - | 1.0 | P |
| MATH 113 | Introduction to Abstract Algebra | Aleksandra Utiralova | 4.0 | A |
| PBHLTH 101 | A Sustainable World: Challenges and Opportunities | Lauren van der Walt, Marlon Maus | 3.0 | A+ |

### Spring 2023
| Course | Description | Instructor | Units | Grade |
|--------|-------------|-----------|-------|-------|
| [COMPSCI 61B](https://sp23.datastructur.es/) | Data Structures | Joshua Hug, Justin Yokota | 4.0 | A |
| [COMPSCI 198](https://decal.ocf.berkeley.edu/) | Directed Group Studies for Advanced Undergraduates | Laksith Prabu, Ben Cuan, Ishaan Dham, Kian Sutarwala, Lance Mathias | 2.0 | P |
| [DATA C8](https://www.data8.org/sp23/) | Foundations of Data Science | Joseph Gonzalez, Swupnil Sahai | 4.0 | A+ |
| GERMAN R5B | Reading and Composition | Mary Hennessy | 4.0 | A |
| MATH 24 | Freshman Seminars | Francisco Grunbaum | 1.0 | P |
| MATH 98BC | Berkeley Connect | - | 1.0 | P |
| NUSCTX 11 | Introduction to Toxicology | Daniel Nomura, Jen Chywan Wang, Sona Kang | 3.0 | A |


### Fall 2022
| Course | Description | Instructor | Units | Grade |
|--------|-------------|------------|-------|-------|
| [COMPSCI 61A](https://cs61a.org/) | The Structure and Interpretation of Computer Programs | John DeNero | 4.0 | A |
| ESPM 50AC | Introduction to Culture and Natural Resource Management | Kurt Spreyer | 4.0 | A+ |
| MATH 55 | Discrete Mathematics | Nikhil Srivastava | 4.0 | A+ |
| NATAMST R1A | Native American Studies Reading and Composition | Sierra Edd | 4.0 | A |

## Random Thoughts

The following paragraphs are all my personal opinions and therefore do not represent the courses I have worked with before, nor Berkeley in general.

As stated on the front page, I am (soon to be a “was”) a computer science and applied mathematics major with a data minor. Entering Berkeley, I was admitted as an Applied Mathematics major, but in high school I had already decided that I would like to add a major in computer science regardless. That’s why you saw that I was enrolled in CS 61A right from the start. At the time, my dad and I were worried that I might not be able to get into it (since it seemed to be the trend that everyone wanted to become a computer science major, no matter what major they had been admitted to Berkeley as). Time proved that thought to be totally incorrect, as it turns out that even if I had wanted to enroll in the course during the adjustment period, I probably still could have gotten in.

As a side story, the trend now seems to be that everyone wants to double major in data science, which is interesting. I guess everyone knows that the job market for software engineering has been tougher in recent years compared to before, and data science is more or less the “sweet” major now. I remember back in the days when I had an infinite amount of time and would see people chatting on WeChat, I would come across at least 50 people claiming that they wanted to add a computer science major (or entirely switch to a computer science major) from their original ones. It was a wild scene—you would see people from film studies, molecular biology, and English all attempting to do so. At the time, I already thought to myself that this seemed a bit corrupted, and that most of them would probably not actually stay in the major. Time proved that thought to be correct, as now, as a senior in computer science, I don’t see many Chinese peers anymore who were there from the start shouting that they wanted to join. Indeed, comprehensive review was Berkeley’s approach to stop this nonsense of everyone transferring majors. I guess that tells one thing: don’t talk before you actually do it. Of course, computer science is a major from which you may end up getting a high-paying job, but the courses are definitely not easy or suited for everyone (especially for folks who want to take it easy but still get good results). With hard work, however, one could major in computer science and still get good grades in the end.

I also enrolled in Math 55, a breadth course, and a writing class, which was the ideal schedule I had designed for myself when coming into this school. You always want to start at a medium pace and then add workload later once you realize you can handle more. Two technical courses and two other requirement courses felt like the ideal start. And that’s how it all began.

In the second semester, I more or less stayed with this approach, as I had two technical courses, one breadth, and one writing course. Data 8, I think, was a compromise due to the fact that I could not enroll in a course I would have liked to take, so I was forced to choose an alternative. It turned out to be a good choice, though, as I really enjoyed the course and ended up adding a data science minor, which I had never envisioned for myself at the beginning of the school year. If you noticed carefully, I also added a bunch of random courses at the time, probably imagining in my head that I would make some new friends. It was a failure—or a disaster. I didn’t make any new friends and started skipping those optional classes I had signed up for. The people I met there seemed to have the same thoughts as me, but at the same time were probably only there for the credits. I never really found the people who fit me and who I would later meet and become friends with.

I also wanted to become the head TA for CS 61A once I learned that undergraduates could become TAs, but that never happened. In fact, I didn’t even get an academic intern offer during my freshman year. I was also interested in research, but as you might guess, I didn’t receive any offers after applying to different programs through URAP during my freshman year. So everything just went okay, with no particularly impressive achievements. Seeing others with impressive accomplishments—whether receiving multiple URAP offers, gaining research experience in their first semester, or becoming academic interns—did not make me feel good, but there wasn’t much I could do at the time. I also had no internship offers while some people were already getting them; the only thing I had was “good grades.” I guess none of it really mattered, since I somewhat became a figure that, when people remember me, they probably see as a cracked figure in the end.

I will continue writing the rest on a different day, as it seems this has already become quite long.